create table country(
    id          bigint generated by default as identity
        primary key,

    name varchar(200),
    continent varchar(255)
);

create table host (
    id          bigint generated by default as identity
        primary key,
    name varchar(200),
    surname varchar(200),
    country_id bigint references country
);


create table Accommodation
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255),
    category varchar(200),
    host_id bigint references host,
    num_Rooms integer,
    isRented boolean default true

);
create table users(
    username                   varchar(255)
        primary key,
        password                   varchar(255),
        name                       varchar(255),
                      surname                    varchar(255),
                      is_account_non_expired     boolean default true,
                      is_account_non_locked      boolean default true,
                      is_credentials_non_expired boolean default true,
                      is_enabled                 boolean default true,
                      role                       varchar(50)

);
create table tempReservation(
    id bigint generated by default as identity
            primary key,
    date_created timestamp,
    user_username varchar(255) references users,
    status varchar(50)

);
create table temp_reservation_accommodations(
    temp_reservation_id bigint references tempReservation on delete cascade,
    accommodation_id bigint references Accommodation on delete cascade,
    primary key (temp_reservation_id,accommodation_id)
);

create index idx_temp_reservation_user_status on tempReservation(user_username,status);
create index idx_user_username_password on users(username,password);
create index idx_user_username on users(username);
create index idx_user_role on users(role);